### PR TITLE
Add latest and modern resources

### PR DESCRIPTION
**Pull request by bhantsi**
This repo exposes amazing resources to me, thus improve my skills and I think it's worth contributing.

### CODE REVIEW

**Comment by bookercodes** [comment]
Hey hey,

Per the [contributing doc](https://learning-resource-path.gitbook.io/resources/contributing), I think you'll increase the chance of these suggestions being included if you submit one suggestion per pull request

**Comment by bhantsi** [comment]
Do you mean one addition, one PR?

**Comment by lauragift21** [comment]
Hi, @bhantsi @bookercodes  I think it's okay for this PR but next time sending in a PR per suggestion will be a better option. I'll go ahead and merge this in.

**Comment by bhantsi** [comment]
> Hi, @bhantsi @bookercodes I think it's okay for this PR but next time sending in a PR per suggestion will be a better option. I'll go ahead and merge this in.

Thank you very much @lauragift21 I will surely do that next time.

**Pull request merged**
