### PR TITLE
Add Vue Developers  to Vue Section

### PR DESCRIPTION
**Pull request by DominusKelvin**
Added a link to [Vue Developers](https://vuejsdevelopers.com/) to the Vue section of the Learning Resource Path. Check out the [repo](https://github.com/DominusKelvin/Learning-Resource-Path-Front-End)

### CODE REVIEW

**Comment by lauragift21** [comment]
Thanks for contributing. 🎉 Please fix the whitespace in the resources types and fix merge conflicts so that I can merge this.

**Comment by DominusKelvin** [comment]
I just did. Everything ok right now?

**Comment by lauragift21** [comment]
Oh I mean each of resources types should retain the whitespace else they'll all be on one line.

**Comment by DominusKelvin** [comment]
Alrighty then

**Comment by DominusKelvin** [comment]
Done.

**Pull request merged**
